# permissions for end users to view counters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: counter-viewer-role
rules:
- apiGroups:
  - app.noroth.io
  resources:
  - counters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.noroth.io
  resources:
  - counters/status
  verbs:
  - get
